name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    #- name: enable debug interface
    #  uses: chn-lee-yumi/debugger-action@master

    - name: Disable debug
      run: |
        sed -i 's/DEBUG = True/DEBUG = False/' cmdb_manager/settings.py

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      
    # https://dev.to/cloudx/multi-arch-docker-images-the-easy-way-with-github-actions-4k54
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        # list of Docker images to use as base name for tags
        images: |
          registry.cn-guangzhou.aliyuncs.com/yumi-cmdb/cmdb-manager
        # Docker tags based on the following events/attributes
        tags: |
          type=ref,event=branch
          type=sha
          
    - name: Login to Aliyun
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        registry: registry.cn-guangzhou.aliyuncs.com
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
          
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        
    #- name: Build Docker image
    #  run: |
    #    docker version
    #    # 登录阿里云镜像仓库
    #    docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} registry.cn-guangzhou.aliyuncs.com
    #    # 使用Dockerfile构建镜像
    #    docker build . --file Dockerfile --tag registry.cn-guangzhou.aliyuncs.com/yumi-cmdb/cmdb-manager:beta
    #    # 推送镜像到镜像仓库
    #    docker push registry.cn-guangzhou.aliyuncs.com/yumi-cmdb/cmdb-manager:beta
