# Generated by Django 4.1.4 on 2022-12-29 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=16)),
            ],
            options={
                "db_table": "group",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "name",
                    models.CharField(max_length=16, primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "project",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=16)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="manager.project",
                    ),
                ),
            ],
            options={
                "db_table": "role",
            },
        ),
        migrations.CreateModel(
            name="Machine",
            fields=[
                (
                    "id",
                    models.CharField(max_length=36, primary_key=True, serialize=False),
                ),
                ("main_ip", models.CharField(max_length=15)),
                ("device_system_info", models.JSONField()),
                ("system_info", models.JSONField()),
                ("cpu_info", models.JSONField()),
                ("memory_info", models.JSONField()),
                ("load_avg", models.JSONField()),
                ("interfaces", models.JSONField()),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="manager.group"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="manager.project",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="manager.role"
                    ),
                ),
            ],
            options={
                "db_table": "machine",
            },
        ),
        migrations.AddField(
            model_name="group",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="manager.project"
            ),
        ),
    ]
