# Generated by Django 4.1.4 on 2022-12-30 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0004_alter_machine_cpu_info_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="manager.project"
            ),
        ),
    ]
