# Generated by Django 4.1.4 on 2022-12-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0005_alter_machine_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="cpu_info",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="machine",
            name="device_system_info",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="machine",
            name="interfaces",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="machine",
            name="load_avg",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="machine",
            name="memory_info",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="machine",
            name="system_info",
            field=models.JSONField(null=True),
        ),
    ]
