# Generated by Django 4.1.4 on 2022-12-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0006_alter_machine_cpu_info_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="last_heartbeat",
            field=models.DateTimeField(null=True),
        ),
    ]
