# Generated by Django 4.1.4 on 2023-01-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0008_project_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
